In [2]:
lst=[10,20,30,40]
print(lst,type(lst))

[10, 20, 30, 40] <class 'list'>


In [3]:
import numpy as np
#to convert list into ndarray
a=np.array(lst)
print("The converted array=",a,type(a))

The converted array= [10 20 30 40] <class 'numpy.ndarray'>


In [4]:
b=np.array([2,3,4,5])
print(b)

[2 3 4 5]


In [6]:
#arange
#s1= varname=numpy.arange(value)
a=np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
b=np.arange(13)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
#s2= varname=numpy.arange(start,stop)
a=np.arange(5,11)
print(a)

[ 5  6  7  8  9 10]


In [13]:
my_marks=np.arange(35,100)
print("The passing marks from 35 to 100=",my_marks)

The passing marks from 35 to 100= [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82
 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [17]:
#s3= varname=numpy.arange(start,stop,step)
a=np.arange(0,21,2)
print("The Even No=",a)

The Even No= [ 0  2  4  6  8 10 12 14 16 18 20]


In [18]:
#to print the odd numbers
b=np.arange(1,21,2)
print("the odd numbers",b)

the odd numbers [ 1  3  5  7  9 11 13 15 17 19]


In [26]:
a=np.arange(0,12,3).reshape(2,2)
print("The Even No=",a)

The Even No= [[0 3]
 [6 9]]


In [30]:
#zeros
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [34]:
a=np.zeros(10,dtype=float)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
#ones
#sn= varname=numpy.ones(value,dtype)

a=np.ones(3)
print(a)

[1. 1. 1.]


In [36]:
a=np.ones(5,dtype=int)
print(a)

[1 1 1 1 1]


In [38]:
a=np.ones((3,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [39]:
a=np.zeros((3,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [40]:
a=np.zeros((2,3,3),dtype=int)
print(a)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [42]:
a=np.zeros((2,2,3,3),dtype=float)
print(a)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]
