creating numpy array

In [1]:
import numpy as np

In [2]:
np.array([2,4,56,422,32,1]) #1d array

array([  2,   4,  56, 422,  32,   1])

In [14]:
a = np.array([2,4,56,422,32,1]) #Vector
a

array([  2,   4,  56, 422,  32,   1])

In [16]:
type(a)

numpy.ndarray

In [23]:
#2D array (matrix)

new = np.array([[45,34,22,2],[24,55,3,22]])
print

array([  2,   4,  56, 422,  32,   1])

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,])

In [4]:
a = np.array([[1,2,3,4],[9,10,11,12]])

In [5]:
print(a[0])

[1 2 3 4]


In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3])

In [8]:
np.zeros(2)

array([0., 0.])

In [11]:
np.ones(2)

array([1., 1.])

In [20]:
#create an empty array with 2 element
np.empty(2)

array([1., 1.])

In [19]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [22]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
x = np.ones(8, dtype=np.int64)
x

array([1, 1, 1, 1, 1, 1, 1, 1])

Adding, removing and sorting element

In [31]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [32]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [40]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])