In [3]:
import numpy as np

In [9]:
np.array([2,3,56,422,32,1]) #1D array

array([  2,   3,  56, 422,  32,   1])

In [11]:
a = np.array([2,4,56,422,32,1])#vector
print(a)

[  2   4  56 422  32   1]


In [12]:
type(a)

numpy.ndarray

In [13]:
new = np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [20]:
#3 D ---# Tensor
np.array ([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

dtype

In [21]:
np.array([11,23,44] , 
dtype =float)

array([11., 23., 44.])

In [22]:
np.array([11,23,44] , 
dtype =bool)

array([ True,  True,  True])

In [26]:
np.array([11,23,44] , dtype = complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

arange

In [28]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [29]:
np.arange(4,45)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44])

In [30]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [31]:
np.arange(1,25,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [33]:
np.arange(25,2)

array([], dtype=int64)

reshape

In [34]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [40]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

ones & zeros

In [44]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.random.random((4,6))

array([[0.57767891, 0.97641828, 0.53952828, 0.28883327, 0.1901845 ,
        0.1823919 ],
       [0.74895437, 0.95853708, 0.92603416, 0.12630247, 0.35580352,
        0.87022037],
       [0.92936092, 0.01644479, 0.2195834 , 0.63318851, 0.07632157,
        0.9603103 ],
       [0.80465495, 0.4839821 , 0.48790011, 0.39272512, 0.16509637,
        0.11991091]])

In [57]:
np.random.random((6,8))

array([[0.42835617, 0.39315115, 0.27963096, 0.92834813, 0.08819931,
        0.80496281, 0.35055695, 0.0882373 ],
       [0.22540961, 0.19774891, 0.40691364, 0.16954918, 0.65635456,
        0.60577158, 0.0190891 , 0.64121584],
       [0.03346142, 0.62713142, 0.53428671, 0.86748197, 0.51977647,
        0.85457434, 0.77798417, 0.51427851],
       [0.89082579, 0.22169428, 0.24878447, 0.93936935, 0.64229955,
        0.04728231, 0.61360004, 0.53379004],
       [0.4363052 , 0.59227453, 0.44922581, 0.83019863, 0.40316178,
        0.41577408, 0.40239245, 0.46966289],
       [0.14298138, 0.43253634, 0.0167689 , 0.31592185, 0.41434505,
        0.83271702, 0.94223227, 0.51064118]])

linspace

In [58]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [59]:
np.linspace(10,10,10)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [60]:
np.linspace(-2,4,6)

array([-2. , -0.8,  0.4,  1.6,  2.8,  4. ])

In [61]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

identity

In [66]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [68]:
np.identity(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [70]:
np.identity(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

Array Attribute 

In [71]:
a1 = np.arange(10)#1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a2 =np.arange(12, dtype =float).reshape(3,4) # Matrix 
a2 

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [73]:
a3 = np.arange(8).reshape(2,2,2) # 3D --> Tensor 
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

ndim

In [75]:
a1.ndim

1

In [76]:
a2.ndim

2

In [78]:
a3.ndim

3

shape

In [79]:
a1.shape

(10,)

In [80]:
a2.shape

(3, 4)

In [81]:
a3.shape

(2, 2, 2)

size

In [82]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [83]:
a3.size

8

In [84]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [85]:
a2.size

12

item size

In [86]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a1.itemsize

8

In [91]:
a1.itemsize

8

In [90]:
a3.itemsize

8

dtype

In [92]:
print(a1.dtype) 
print(a2.dtype) 
print(a3.dtype)

int64
float64
int64


changing data type

In [94]:
x = np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [96]:
x.astype(int)

array([33, 22,  2])

array operations

In [97]:
z1 = np.arange(12).reshape(3,4) 
z2 = np.arange(12,24).reshape(3,4)

In [98]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

scalar operations

In [100]:
z1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [101]:
z1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [102]:
z1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [103]:
z1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [104]:
z1 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

relational operators

In [105]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [106]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

vector operaton

In [107]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [109]:
z1 + z2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [110]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [111]:
z1 ** z2


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [112]:
z1 % z2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array function

In [113]:
k1 = np.random.random((3,3)) 
k1 = np.round(k1*100) 
k1

array([[81., 77., 12.],
       [48.,  4., 69.],
       [36., 26., 15.]])

In [114]:
np.min(k1)

np.float64(4.0)

In [115]:
np.max(k1)

np.float64(81.0)

In [116]:
np.sum(k1)

np.float64(368.0)

In [117]:
np.max(k1, axis = 0)

array([81., 77., 69.])

In [118]:
np.prod(k1, axis = 0)

array([139968.,   8008.,  12420.])

Statistics related fuctions

In [119]:
k1

array([[81., 77., 12.],
       [48.,  4., 69.],
       [36., 26., 15.]])

In [120]:
np.min(k1)

np.float64(4.0)

In [121]:
np.sum(k1)

np.float64(368.0)

In [123]:
np.mean(k1)

np.float64(40.888888888888886)

In [124]:
np.median(k1, axis = 1) 


array([77., 48., 26.])